const template = {
    id: 'light',
    name: 'Light',
    values: {
        appBgColor: {name: 'app-bg-color', variable: 'app-bg-color', value: 'APPBGCOLOR'},
        appAccentColor: {name: 'app-accent-color', variable: 'app-accent-color', value: 'APPACCENTCOLOR'},
        primaryTextColor: {name: 'primary-text-color', variable: 'primary-text-color', value: 'PRIMARYTEXTCOLOR'},
        secondaryTextColor: {name: 'secondary-text-color', variable: 'secondary-text-color', value: 'SECONDARYTEXTCOLOR'},
        warningTextColor: {name: 'warning-text-color', variable: 'warning-text-color', value: 'WARNINGCOLOR'},
        errorTextColor: {name: 'error-text-color', variable: 'error-text-color', value: 'DANGERCOLOR'},
        primaryButtonBgColor: {name: 'primary-button-bg-color', variable: 'primary-button-bg-color', value: 'APPACCENTCOLOR'},
        primaryButtonTextColor: {name: 'primary-button-text-color', variable: 'primary-button-text-color', value: 'PRIMARYTEXTCOLOR'},
        secondaryButtonBgColor: {name: 'secondary-button-bg-color', variable: 'secondary-button-bg-color', value: 'SECBUTTONCOLOR'},
        secondaryButtonTextColor: {name: 'secondary-button-text-color', variable: 'secondary-button-text-color', value: 'PRIMARYTEXTCOLOR'},
        warningButtonBgColor: {name: 'warning-button-bg-color', variable: 'warning-button-bg-color', value: 'WARNINGCOLOR'},
        warningButtonTextColor: {name: 'warning-button-text-color', variable: 'warning-button-text-color', value: 'WARNBUTTONTEXTCOLOR'},
        dangerButtonBgColor: {name: 'danger-button-bg-color', variable: 'danger-button-bg-color', value: 'DANGERCOLOR'},
        dangerButtonTextColor: {name: 'danger-button-text-color', variable: 'danger-button-text-color', value: 'PRIMARYTEXTCOLOR'},
        dividerColor: {name: 'panel-divider-color', variable: 'panel-divider-color', value: 'DIVIDERCOLOR'},

        panelBgColor: {name: 'panel-bg-color', variable: 'panel-bg-color', value: 'APPBGCOLOR'},
        panelAccentColor: {name: 'panel-accent-color', variable: 'panel-accent-color', value: 'APPACCENTCOLOR'},
        panelDividerColor: {name: 'panel-divider-color', variable: 'panel-divider-color', value: 'DIVIDERCOLOR'},
        panelTitleTextColor: {name: 'panel-title-text-color', variable: 'panel-title-text-color', value: 'PRIMARYTEXTCOLOR'},
        panelPrimaryTextColor: {name: 'panel-primary-text-color', variable: 'panel-primary-text-color', value: 'PRIMARYTEXTCOLOR'},
        panelSecondaryTextColor: {name: 'panel-secondary-text-color', variable: 'panel-secondary-text-color', value: 'SECONDARYTEXTCOLOR'},
        panelPrimaryButtonBgColor: {name: 'panel-primary-button-bg-color', variable: 'panel-primary-button-bg-color', value: 'APPACCENTCOLOR'},
        panelPrimaryButtonTextColor: {name: 'panel-primary-button-text-color', variable: 'panel-primary-button-text-color', value: 'PRIMARYTEXTCOLOR'},
        panelSecondaryButtonBgColor: {name: 'panel-secondary-button-bg-color', variable: 'panel-secondary-button-bg-color', value: 'SECBUTTONCOLOR'},
        panelSecondaryButtonTextColor: {name: 'panel-secondary-button-text-color', variable: 'panel-secondary-button-text-color', value: 'PRIMARYTEXTCOLOR'},
        panelWarningButtonBgColor: {name: 'panel-warning-button-bg-color', variable: 'panel-warning-button-bg-color', value: 'WARNINGCOLOR'},
        panelWarningButtonTextColor: {name: 'panel-warning-button-text-color', variable: 'panel-warning-button-text-color', value: 'WARNBUTTONTEXTCOLOR'},
        panelDangerButtonBgColor: {name: 'panel-danger-button-bg-color', variable: 'panel-danger-button-bg-color', value: 'DANGERCOLOR'},
        panelDangerButtonTextColor: {name: 'panel-danger-button-text-color', variable: 'panel-danger-button-text-color', value: 'PRIMARYTEXTCOLOR'},

        cardBgColor: {name: 'card-bg-color', variable: 'card-bg-color', value: 'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWDONTFORGETTHISONE'},
        cardAccentColor: {name: 'card-accent-color', variable: 'card-accent-color', value: 'APPACCENTCOLOR'},
        cardDividerColor: {name: 'card-divider-color', variable: 'card-divider-color', value: 'DIVIDERCOLOR'},
        cardTitleTextColor: {name: 'card-title-text-color', variable: 'card-title-text-color', value: 'PRIMARYTEXTCOLOR'},
        cardPrimaryTextColor: {name: 'card-primary-text-color', variable: 'card-primary-text-color', value: 'PRIMARYTEXTCOLOR'},
        cardSecondaryTextColor: {name: 'card-secondary-text-color', variable: 'card-secondary-text-color', value: 'SECONDARYTEXTCOLOR'},
        cardPrimaryButtonBgColor: {name: 'card-primary-button-bg-color', variable: 'card-primary-button-bg-color', value: 'APPACCENTCOLOR'},
        cardPrimaryButtonTextColor: {name: 'card-primary-button-text-color', variable: 'card-primary-button-text-color', value: 'PRIMARYTEXTCOLOR'},
        cardSecondaryButtonBgColor: {name: 'card-secondary-button-bg-color', variable: 'card-secondary-button-bg-color', value: 'SECBUTTONCOLOR'},
        cardSecondaryButtonTextColor: {name: 'card-secondary-button-text-color', variable: 'card-secondary-button-text-color', value: 'PRIMARYTEXTCOLOR'},
        cardWarningButtonBgColor: {name: 'card-warning-button-bg-color', variable: 'card-warning-button-bg-color', value: 'WARNINGCOLOR'},
        cardWarningButtonTextColor: {name: 'card-warning-button-text-color', variable: 'card-warning-button-text-color', value: 'WARNBUTTONTEXTCOLOR'},
        cardDangerButtonBgColor: {name: 'card-danger-button-bg-color', variable: 'card-danger-button-bg-color', value: 'DANGERCOLOR'},
        cardDangerButtonTextColor: {name: 'card-danger-button-text-color', variable: 'card-danger-button-text-color', value: 'PRIMARYTEXTCOLOR'},
    }
},